name = "chaplin"
version = "1.0.0"
licences = ["Apache-2.0"]
description = "Mustache text templates using Erlang's bbmustache package"

repository = { type = "github", user = "lpil", repo = "chaplin", tag-prefix = "chaplin-" }
links = [
  { title = "Mustache", href = "https://mustache.github.io/" },
  { title = "bbmustache", href = "https://github.com/soranoba/bbmustache" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
bbmustache = ">= 1.12.2 and < 2.0.0"
gleam_stdlib = ">= 0.62.1 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.6.1 and < 2.0.0"
