name: test

on:
  push:
    branches:
      - 'main'
      - 'v*.*.*'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "23.2"
          gleam-version: "0.30.5"
      - run: gleam test
      - run: gleam format --check src test
